name: Deploy to EB

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create ZIP deployment package
        run: zip -r deploy_package.zip ./ -x "**node_modules**"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "sa-east-1"

      - name: Upload package to S3 bucket
        run: aws s3 cp deploy_package.zip s3://sunky-app/
      
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
      
      - name: Run string replace
        uses: frabert/replace-string-action@v2.0
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name sunky-app \
          --source-bundle S3Bucket="sunky-app",S3Key="deploy_package.zip" \
          --version-label "sunky-app-${{ steps.format-time.outputs.replaced }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name Sunkyapp-env-1 --version-label "sunky-app-${{ steps.format-time.outputs.replaced }}"
